[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
viaIR = true
optimizer = true
optimizer_runs = 100

[rpc_endpoints]
mainnet = "${RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api" }
